name: "My JavaScript Action"
description: "A sample GitHub Action written in JavaScript"
author: "Your Name"
inputs:
  my-input:
    description: "An input parameter for the action"
    required: true
    default: "default-value"

outputs:
  my-output:
    description: "An output from the action"

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  color: "blue"
  icon: "zap"
